apiVersion: v1
kind: Service
metadata:
 name: app-service
 namespace: default
spec:
 selector:
    app: app-deployment
 ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
 type: ClusterIP