apiVersion: batch/v1
kind: CronJob
metadata:
 name: clear-cache-cronjob
 namespace: default
spec:
 schedule: "2 * * * *"
 jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: clear-cache
            image: curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - |
              curl -X DELETE http://app-service:8080/v1/cache
            startupProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 5
              failureThreshold: 3
          restartPolicy: OnFailure