server:
  port: 8080
  allowOrigins:
    - "*"
  bodyLimit: "10M" # MiB
  timeout: 30 # Seconds
  
redis:
  host: localhost
  port: 6379

database:
  host: 0.0.0.0
  port: 3306
  user: root
  password: Pass1234
  dbname: never-db