server:
  port: 8080
  allowOrigins:
    - "*"
  bodyLimit: "10M" # MiB
  
redis:
  masterName: mymaster
  password: admin
  sentinelAddrs:
    - localhost:5000

database:
  host: localhost
  port: 3306
  user: root
  password: Pass1234
  dbname: mydb