server:
  port: 8080
  allowOrigins:
    - "*"
  bodyLimit: "10M" # MiB
  
redis:
  host: localhost
  port: 6379

database:
  host: localhost
  port: 3306
  user: root
  password: Pass1234
  dbname: mydb