apiVersion: v1
kind: Service
metadata:
  name: sentinel
  namespace: default
spec:
  selector:
    app: sentinel
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    name: sentinel
  type: ClusterIP